name: Run code validation

on:
  # Triggers the workflow on push or pull request events for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validateJs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.18.0, 16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # Install dependencies with npm ci
      - run: npm ci
      - run: for i in test/*.js; do npx eslint $i; done
      # - run: for i in *.js; do npx eslint $i; done