name: Cypress Tests

on: 
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up credentials.json
        run: echo '${{ secrets.CREDENTIALS_JSON }}' > credentials.json

      - name: Start Node.js server
        run: |
          npm install
          node index.js &
      - name: Wait for server to start
        run: |
          while ! curl -s http://127.0.0.1:8080/NTIBusScreen/ > /dev/null; do sleep 1; done
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true # Runs test in parallel using settings above
        env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}